[platformio]
default_envs = mega2560_bringup
src_dir = sketches/TurnoutBringup
lib_dir = lib

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2

[env:mega2560_bringup]
platform = atmelavr
board = megaatmega2560

[env:uno_bringup]
platform = atmelavr
board = uno
